---
- hosts: localhost
  become: no
  gather_facts: no
  tasks:
    - name: ""
      terraform:
        project_path: "{{ playbook_dir }}/../../terraform/modules/ncp-postinstall-snapshot-provider"
        variables_file: "{{ playbook_dir }}/../../terraform/terraform.tfvars"
        variables:
          branch: "{{ branch }}"

  vars: []