name: Release Runner Image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag to use for the image
        required: true
        default: 'latest'
        type: string

env:
  IMAGE_NAME: ncp-test-automation
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build . --tag "$IMAGE_NAME"

      - name: Login to docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: Push image
        run: |
          IMAGE="$(echo "ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}" | tr '[A-Z]' '[a-z]')"
          for tag in "${{ github.run_id }}" "${{ github.event.inputs.tag }}"
          do
            docker tag "${IMAGE_NAME}" "${IMAGE}:${tag}"
            docker push "${IMAGE}:${tag}"
          done
